# Generated by Django 3.2.7 on 2021-11-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211112_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='video',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
