# Generated by Django 3.2.7 on 2021-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facebook',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='map',
            field=models.CharField(max_length=1000),
        ),
    ]
