# Generated by Django 3.2.7 on 2021-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211113_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
