# Generated by Django 3.2.7 on 2021-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('job', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
