# Generated by Django 3.2.7 on 2021-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='abus',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='abus_content',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='abus_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
