# Generated by Django 3.2.7 on 2021-11-19 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_abus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='abus_content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
