# Generated by Django 3.2.7 on 2021-11-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcate',
            name='pub_date',
        ),
    ]
