# Generated by Django 3.2.7 on 2021-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productcate_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcate',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productcate',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
