# Generated by Django 3.2.7 on 2021-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211112_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='intro',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productcate',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
