# Generated by Django 3.2.7 on 2021-11-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='content',
        ),
    ]
