# Generated by Django 3.2.7 on 2021-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
