# Generated by Django 3.2.7 on 2021-11-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211114_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
