# Generated by Django 3.2.7 on 2021-11-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_new_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='category',
        ),
    ]
