# Generated by Django 3.2.7 on 2021-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_title_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
