# Generated by Django 3.2.7 on 2021-11-16 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_rename_desciption_new_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 22, 26, 35, 236015)),
        ),
    ]
