# Generated by Django 3.2.7 on 2021-11-17 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20211117_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 0, 45, 32, 907581)),
        ),
    ]
